### ISSUE TITLE
Cek Voucher

### ISSUE THREAD

**Issue by ChandraOrbit** [laksa19/mikhmonv2#1]
Pada template Login Hotspot Mikhmon ada fitur Cek Voucer oleh client, implementasinya bagaimana dengan Mikhmon V2 ?

**Comment by laksa19** [comment]
1. Download plugin status di https://laksa19.github.io/download/plugin/status.zip. Extract file tersebut dan copy paste ke folder mikhmonv2.
2. Edit file detail.html (hotspot3 atau hotspot4). Cari baris 15 `<iframe style="border:none;" height="500" width="100%" src="http://ip-webserver-mikhmon:port/mikhmon/status"></iframe>`.
3. Sesuaikan pada bagian `src="http://ip-webserver-mikhmon:port/mikhmonv2/status"`. 
Contoh : `src="http://192.168.1.3:8080/mikhmonv2/status"` atau jika menggunakan port 80 `src="http://192.168.1.3/mikhmonv2/status"`

**Comment by ChandraOrbit** [comment]
Berarti untuk MikhmonV2 harus online terus ya bang

**Comment by laksa19** [comment]
Kalau pengennya bisa akses setiap saat, ya harus. Kembali lagi dengan keadaan dan kebutuhan di tempat Anda.

**Comment by ChandraOrbit** [comment]
OK, logika saya mau saya implementasikan dengan LEDE agar bisa Online terus..

**Comment by laksa19** [comment]
Saya juga pakai LEDE Pulpstone untuk web servernya.

**Comment by ChandraOrbit** [comment]
Untuk radionya yg stabil utk pasang LEDE Pulpstone apa ya bang, sekalian bisa buat AP hotspot

**Comment by laksa19** [comment]
Saya tidak tau banyak tentang hal itu, saya pakai huawei hg553.

**Comment by ChandraOrbit** [comment]
OK makasih inponya

**Comment by laksa19** [comment]
Pelajari walled garden ip list. Masukkan ip sever Mikhmon di sana.

**Comment by ChandraOrbit** [comment]
makasih bang
