### ISSUE TITLE
(request) setting quota berjenjang

### ISSUE THREAD

**Issue by ChandraOrbit** [laksa19/mikhmonv2#2]
Hi bang, 
Saya mau request atau mungkin sayanya yg masih belum paham penggunaan Mikhmon.

Study kasus dengan system Quota/data limit, Limit time dan Validaty, Template Hotspot-4
- Quota/data limit 5 Gb, Limit Time 3 hari dan Validaty 1 minggu 
jika 5 Gb tercapai dan limit time masih sisa maka user tdk bisa login dengan keterangan Voucer Expirate.
Jika Limit Time tercapai dan data limit masih sisa, user tdk bisa login dengan keterangan Voucer Expirate.

Setingan yg diharapkan.
- jika 5 Gb tercapai dan Limit Time nya masih sisa maka user tetap bisa login dgn BW kecil atau hanya bisa browsing google saja. sampai Limit Time atau Validaty tercapai.

seperti [DISINI](http://www.mikrotik.co.id/artikel_lihat.php?id=132)

Terima kasih sebelumnya.

**Comment by laksa19** [comment]
Yang diharapkan sepertinya tidak akan ada, karena keterbatasan user profile hotspot yang tidak sama dengan radius userman.

**Comment by ChandraOrbit** [comment]
OK bang makasih, 
krn di tempat saya skitar 15 pelanggan (tetangga semua), request bgt jd bingung hrs gmn ..sedangkan RB saya versi lite ga support Userman.

**Comment by laksa19** [comment]
1. Kenapa menerapkan sistem time limit dan data limit?
2. Bukannya lebih gampang validity saja, habis ya habis, harus bayar lagi.

**Comment by ChandraOrbit** [comment]
Kemauan user pengen seperti Provider GSM bang, jadi wl quota habis masih bisa browsing wl cuma google saja sampai batas waktu masa aktifnya habis.
