### ISSUE TITLE
Bug Print Voucher

### ISSUE THREAD

**Issue by ChandraOrbit** [laksa19/mikhmonv2#3]
Bang ada Bug Print Voucher
1. Jika selesai Add User dan SAVE trus langsung di Print tidak masalah, namun formatnya adalah Thermal
2. Jika Print nya setelah Close Add USER, pada User List maka akan masalah pada voucer, yaitu Kode Voucher dan Keterangan dibawahnya tidak akan muncul.

Trial Error
Point -2 akan sukses jika Comment nya diawali dengan "up-"

**Comment by ChandraOrbit** [comment]
ohh maaf, karena ga ada keterangan kenapa dibuat begitu

**Comment by laksa19** [comment]
Untuk print kembali user yang telah di add, masuk ke user list pilih salah user yang ingin di print.

**Comment by ChandraOrbit** [comment]
OK paham, 
Pemahaman saya dgn cara begini kalau tdk salah dimaksudkan untuk MEMBER Langganan yg akan memperpanjang layanan. 
jadi fungsi Comment untuk keterangan buat kita saja. 
dan tidak bisa langsung Print dari USER LIST harus dibuka USER nya dl.

Makasih
