### ISSUE TITLE
(request) fitur

### ISSUE THREAD

**Issue by ChandraOrbit** [laksa19/mikhmonv2#4]
maaf saya yg newbie, 
ada pelanggan saya yg request, bisa ga 1 voucher hanya utk 1 device, jd ada kalanya voucher yg sdh dibeli trs vouchernya dibuang, trs sm orang lain kode voucher itu dipakai. sedangkan si pembeli waktu itu sdh logout. 

saya googling dapat script ini

> 
:local date [/system clock get date];
:local time [/system clock get time];
:log info “”
:log warning “$user login jam $time”;
:log info “”
{
:if ( [ /ip hotspot user get $user comment ] = “” ) do={
[ /ip hotspot user set $user comment=TERPAKAI]
}
}
:foreach i in=[/ip hotspot active find] do={
local mac [/ip hotspot active get $i mac-address]
:log info “”
log info “mac $mac”
:log info “”
/ip hotspot user set mac-address=$mac [find name=$user]
}
system scheduler add name=$user start-time=”$time” interval=12:00:00 policy=read,write on-event=”ip hotspot user remove [find name=$user]\r\nip hotspot active remove [find user=$user]\r\nsystem scheduler remove [find name=$user]”

yang saya pahami itu memberikan penandaan pada user yg aktif lalu mac adressnya di disematkan dalam user tersebut, sehingga saat logout pun, kode voucher tdk dapat digunakan orang lain.

Mohon saran, kira2 script tsb saya masukan bagian mana pada MIKHMON. saya awam banget ttg coding.
Dan jika kalau boleh request, agar fitur tsb dimasukan dalam featur Mikhmon.

Terimakasih dan maaf atas ketidakpahaman saya.

**Comment by laksa19** [comment]
Mungkin akan ditambahkan fitur lock MAC di update selanjutnya.

**Comment by ChandraOrbit** [comment]
:))
Ditunggu Updatenya
Untuk sementara saat ini saya tambahin script secara manual pada User Profil di On Login, khususnya User Profil yang untuk 1 User, Untuk yg lebih dari 1 User tidak saya Lock krn saya ga tau Scriptnya bagaimana.
Hanya kendala, jika 1 User menggunakan lebih dari 1 Device (ex. HP dan Laptop) dan ingin menggunakan voucer yg sama tidak bisa krn sdh ter Lock Mac Adressnya utk 1 Device.

Ini Script yg saya tambahkan dari hasil googling :
`:local used $user;:local mac [/ip hotspot active get [find user=$used] mac-address];[/ip hotspot user set $used mac=$mac];:log info message=("User $used telah dilock dengan mac-address: $mac")}`

**Comment by laksa19** [comment]
tidak perlu, saya bisa buat sendiri.

**Comment by ChandraOrbit** [comment]
OK maaf saya cm share saja, jika emg berguna kl ga jg gpp.
makasih, sukses slalu bang
