### ISSUE TITLE
tidak bisa download

### ISSUE THREAD

**Issue by tryhardtheis** [laksa19/mikhmonv2#6]
Mas file Mikhmon mikhmonv2/js/adminlte.js teridentifikasi virus Trojan:Win32/Spursint.F!cl
apakah tidak bisa di chek saya tidak bisa download. terima kasih

**Comment by laksa19** [comment]
Itu download file yang mana?

**Comment by tryhardtheis** [comment]
File ini mas dari website mas . 
https://raw.githubusercontent.com/laksa19/laksa19.github.io/master/download/mikhmonv2ws.zip
https://github.com/laksa19/mikhmonv2/archive/master.zip
https://raw.githubusercontent.com/laksa19/laksa19.github.io/master/download/update.zip

ketiga file ini

**Comment by laksa19** [comment]
waduh, di saya aman aman saja, tidak ada masalah terdeteksi virus.

**Comment by tryhardtheis** [comment]
soalnya saya menggunakan antivirus win defender mas dan selalu di update, oyah mah ini bisa running di linux juga kan?

**Comment by laksa19** [comment]
Saya cek juga bersih.

**Comment by laksa19** [comment]
Sama saya juga menggunakan anti virus win defender.
Dan saya cek di virustotal hasilnya bersih.
![pageshot of virustotal 2018-06-04-0840 40](https://user-images.githubusercontent.com/16347475/41073926-c7aa8246-6a2f-11e8-8f35-0c26d8fc8186.png)
![pageshot of virustotal 2018-06-04-0840 09](https://user-images.githubusercontent.com/16347475/41073927-c7f5d7aa-6a2f-11e8-9606-80f012927c76.png)
![pageshot of virustotal 2018-06-04-0836 55](https://user-images.githubusercontent.com/16347475/41073929-c833e892-6a2f-11e8-9fb0-dad929b3a016.png)
![pageshot of virustotal 2018-06-04-0841 13](https://user-images.githubusercontent.com/16347475/41073930-c86c0498-6a2f-11e8-97aa-ddaff76eea51.png)

**Comment by tryhardtheis** [comment]
ok mas. thx buat infonya
